# Generated by Django 4.1.5 on 2023-01-10 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
                (
                    "measurement",
                    models.CharField(
                        choices=[("unidade", "Un"), ("gramas", "Gr")], max_length=100
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
