# Generated by Django 4.1.5 on 2023-01-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="function",
            field=models.CharField(
                choices=[
                    ("Cozinheiro", "Cozi"),
                    ("Caixa", "Caixa"),
                    ("Entregador", "Entre"),
                    ("Serviços Gerais", "Serv Ger"),
                    ("Gerente", "Ger"),
                    ("Administrador", "Adm"),
                ],
                max_length=50,
            ),
        ),
    ]
