# Generated by Django 4.1.5 on 2023-01-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
