# Generated by Django 4.1.5 on 2023-01-10 14:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=250)),
                ("price", models.FloatField()),
                ("image", models.CharField(max_length=250, null=True)),
                ("orders_num", models.IntegerField(default=0, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngredientsToDish",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                (
                    "measurement",
                    models.CharField(
                        choices=[("unidade", "Un"), ("gramas", "Gr")], max_length=100
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DishIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dishes.dish"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dishes.ingredientstodish",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dishes",
                through="dishes.DishIngredient",
                to="dishes.ingredientstodish",
            ),
        ),
    ]
