# Generated by Django 4.1.5 on 2023-01-10 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=50)),
                ("cpnj", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(max_length=127, unique=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
    ]
