# Generated by Django 4.1.5 on 2023-01-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table", models.CharField(max_length=50, null=True)),
                ("total", models.FloatField()),
                ("dishes_info", models.CharField(max_length=2000, null=True)),
                (
                    "pay_method",
                    models.CharField(
                        choices=[
                            ("credit", "Cr"),
                            ("debit", "Db"),
                            ("cash", "Ch"),
                            ("pix", "Px"),
                        ],
                        max_length=50,
                    ),
                ),
                ("delivery", models.BooleanField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("doing", "Doing"),
                            ("delivered", "Delivered"),
                            ("canceled", "Canceled"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="clients.client",
                    ),
                ),
                (
                    "dishes",
                    models.ManyToManyField(related_name="orders", to="dishes.dish"),
                ),
            ],
        ),
    ]
